config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "pages#home"
get 'pages/home', to: 'pages#home'

resources :recipes

get '/signup', to: 'chefs#new'
resources :chefs, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chef.rb
class Chef < ApplicationRecord
	before_save { self.email = email.downcase}
	validates :chefname, presence: true, length: {maximum: 30}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255},
                   format:{with: VALID_EMAIL_REGEX},
                   uniqueness: {case_sensitive: false}

has_many :recipes, dependent: :destroy  
has_secure_password
validates :password, presence: true, length: { minimum: 5 }, allow_nil: true

end

app/models/chef_test.rb
require 'test_helper'

class ChefTest < ActiveSupport::TestCase
	
	def setup
	@chef = Chef.new(chefname:"jose", email:"jajosemiguel@gmail.com", 
		password: "password", password_confirmation: "password")
	end

	test "Should ve balid" do
		assert @chef.valid?
	end

	test "name should be present" do
      @chef.chefname = " "
      assert_not @chef.valid?
	end

	test "name should be less than 30 characters" do
		@chef.chefname = "a" * 31
		assert_not @chef.valid?
	end
	test "email should not be too long" do
		@chef.email ="a" * 245 + "@gmail.com"
		assert_not @chef.valid?
	end
	test "email should accept be correct format" do
		valid_emails = %w[user@example.com jajosemiguel@gmail.com]
		valid_emails.each do |valids|
		@chef.email = valids
		assert @chef.valid?, "#{valids,inspect} should be valid"
	  end
	end
    test "should reject invalid addresses" do |
    	invalid_emails = %w[jajosemiguel@gmail.com, america8362@hotmail.com]
    	invalid_emails.each do |invalids|
    		@chef.email =invalids
    		assert_not @chef.valid?, "#{invalids.inspect}should be invalid"
        end
    end

    test "email should be unique and case insensitive" do
    	duplicate_chef = @chef.dup
    	duplicate_chef.email = @chef.email.upcase
    	@chef.save
    	assert_not duplicate_chef.valid?
    end

    test "email should be lower case before hitting db" do
    	mixed_email = "jalvarado@ewn.com.mx"
    	@chef.email = mixed_email
    	@chef.save
    	assert_equal mixed_email.downcase, @chef.reload.email
    end
    test " password should be present" do
    	@chef.password = @chef.password_confirmation = " "
    	assert_not @chef.valid?
    end
     
     test " password_confirmation should be atleast 5 character" do
     	@chef.password = @chef.password_confirmation = " x" * 4
     	assert_not @chef.valid?
     end
     test " associated recipes should be destroyed" do
        @chef.save
        @chef.recipes.create!(name: "testing destroy", description: "testing destroy function")
        @assert_difference "Recipe.count", -1 do
            @chef.destroy
        end
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord

validates :name, presence: true
validates :description, presence:true, length: {minimum: 5, maximum: 500}
belongs_to :chef
validates :chef_id, presence: true
default_scope -> {order(updated_at: :desc)}

end

app/models/recipe_test.rb
require 'test_helper'

class RecipeTest < ActiveSupport::TestCase
	
	def setup

		@chef = Chef.create!(chefname: "Jose", email: "jajosemiguel@gmail.com",
			     password: "password", password_confirmation: "password")
		@recipe = @chef.recipes.build(name: "vegetable",description:"great vegetable recipe", chef_id: @chef.id)
	
	end
	test "recipe without chef should be invalid" do
      @recipe.chef_id = nil
      asser_not @recipe.valid?
	end

    test "recipe should be valid" do
    assert @recipe.valid?
     end
 
  test "name should be present " do
  @recipe.name = " "
  asser_not @recipe.valid?
 end

  test "description should be present " do
  @recipe.description = " "
  asser_not @recipe.valid?
 end
 test "description shouldn't be less than 5 characters" do
 @recipe.description = "a" * 3 
 asser_not @recipe.valid?
 end
test "description shouldn't be more than 500 characters" do
@recipe.description = "a" * 501
asser_not @recipe.valid?

end
test " email should be present" do
	@chef.email = " "
	asser_not @chef.valid?
	@chef.save
	asser_not duplicate_chef.valid?
end
test "email should be lower case before hitting db" do
	mixed_email = "jajosemiguel@gmail.com"
	@chef.email = mixed_email
	@chef.save
	assert_equal mixed_email.downcase, @chef.reload.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  
  def index 
       @chefs = Chef.paginate(page: params[:page], per_page: 5) 
  end


  def new
	@chef = Chef.new

  end
  def create
  	@chef = Chef.new(chef_params)
  	if @chef.save
  		flash[:success] = "Welcome #{@chef.chefname} to MyRecipes App!"
  		redirect_to chef_path(@chef)
  	else
  		render 'new'
  	end
  end
  
  def show
  	@chef = Chef.find(params[:id])
    @chef_recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end
  
  def edit
    @chef = Chef.find(params[:id])
  end
  def update
   @chef = Chef.find(params[:id]) 
   if @chef.update(chef_params)
       flash[:success] = "Your account was updated successfully"
       redirect_to@chef
     else
      render 'edit'
    end
  end
  def destroy
    
    @chef = Chef.find(params[:id])
    @chef.destroy
    flash[:danger] = "Chef and all associated rescipes have been deleted!"
    redirect_to chefs_path
  end
  private

  def chef_params
  	params.require(:chef).permit(:chefname, :email, :password, :password_confirmation)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
def home
	
end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :set_recipe, only: [:show, :edit, :update]

  def index
       @recipes = Recipe.paginate(page: params[:page], per_page: 5) 
  end

  def show
  
  end
  
  def new
  	@recipe = Recipe.new
  end
  
  def create
  	@recipe = Recipe.new(recipe_params)
  	@recipe.chef = Chef.first
  	if @recipe.save
  		flash[:success] = "Recipe was created successfully!"
  		redirect_to recipe_path(@recipe)
  		else
  			render 'new'
  	end
  end

  def edit
   end

  def update
  if @recipe.update(recipe_params)
  	flash[:success] = "Recipe was updated successfully"
  	redirect_to recipe_path(@recipe)
   else
   render 'edit'	
  end
end

def destroy
  Recipe.find(params[:id]).destroy
  flash[:success] = "Recipe deleted successfully"
  redirect_to recipes_path
end

private

def set_recipe
  @recipe = Recipe.find(params[:id])
end
	def recipe_params
		params.require(:recipe).permit(:name, :description)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def gravatar_for(user, options = {size:80})
	gravatar_id =  Digest::MD5::hexdigest(user.email.downcase)
	size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.chefname,class: "img-circle")
 end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@chef, :html => {class: "form-horizontal", role: "form"})do |f| %>
          <div class="form-group">
            <div class="control-label col-md-2">
              <%= f.label :chefname, "Choose Chefname" %>
            </div>
            <div class="col-md-8">
              <%= f.text_field :chefname, class: "form-control", placeholder: "Enter your name", autofocus: true %>	
            </div>
         </div>
         <div class="form-group">
           <div class="control-label col-md-2">
           	 <%= f.label :email %>
           </div>
           <div class="col-md-8">
           	  <%= f.email_field :email, class: "form-control",placeholder: "Enter your email" %>
           </div>
             <div class="form-group">
           <div class="control-label col-md-2">
           	 <%= f.label :password %>
           </div>
           <div class="col-md-8">
           	  <%= f.password_field :password, class: "form-control",placeholder: "Choose a password" %>
           </div>
           <div class="form-group">
           <div class="control-label col-md-2">
           	 <%= f.label :password_confirmation, "Confirm Password" %>
           </div>
           <div class="col-md-8">
           	  <%= f.password_field :password_confirmation, class: "form-control",placeholder: "Confirm password" %>
           </div>

           <div class="form-group">
           	  <div class="col-md-offset-2 col-md-10">
           	  	<%= f.submit(@chef.new_record? ? "Create my account" : "Update my account", class: "btn btn-primary btn-lg btn-xlarge") %>
           	  </div>
           </div>
        <% end %> 
        <div class=" col-md-4 col-md-offset-4 colormatch">
        	<%= link_to "cancel request and return to recipes listing"%>
        </div> 
    </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: " Edit your profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>

<div align="center">
	<%= will_paginate %>
	 <%= @chefs.each do |chef| %>
	  <ul class="listing">
	    <div class="row">
	      <div class="well col-md-4 col-md-offset-4">
	        <li><%= link_to gravatar_for(chef), chef_path(chef) %></li>
	        <li class="chef-title"><%= link_to chef.chefname.capitalize, chef_path(chef) %></li>
	    	<li><small><%= pluralize(chef.recipes.count, "recipe")if chef.recipes %></small></li>
	    	<li><%= link_to "Delete this chef", chef_path(chef), method: :delete,
	    	        data: {confirm: "Are you sure you want to delete the chef and all associated recipes?"} %></li>
	      </div>
	    </div>
	   </ul> 
	<% end %>
  <%= will_paginate %>  
</div>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Sign up for the application" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef #{@chef.chefname}'s profile" %>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
		<%= gravatar_for @chef, size: 150 %>
	</div>
</div>

<h4 align="center"><%= @chef.chefname %>'s recipes</h4>
<div align= "center"></div>
  <%= will_paginate @chef_recipes %>
</div>
<%= render 'recipes/recipe', obj: @chef_recipes %>
<div align= "center"></div>
  <%= will_paginate @chef_recipes %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
	<strong><a href="http://www.clubamerica.com"> Matacode Development Training</a></strong>
	by <em><a href="www.maxipet.net">Jose Miguel</a></em>
</small>
<nav>
	<ul>
		<li><%= link_to "About", '#' %></li>
	</ul>
</nav>
</footer>

app/views/layouts/_messages.html.erb
 <div class="row">
  <div class="col-md-10 col-md-offset-1">
  	<% flash.each do |name, msg| %>
  	<div class="alert alert-<%= name %>">
  		<a href="#" class="close" data-dismiss="alert">&#215;</a>
         <%= msg %>       
  	</div>
  <% end %>
 </div> 	
</div>
 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyRecipes", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs", chefs_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Create a new recipe", new_recipe_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>Welcome to MyRecipes</h1>
	<h2>The best recipe sharing app!</h2>
	<p><%= link_to "Sign up for the app",signup_path, class: "btn btn-danger btn-lg tbtn-xlarge" %></p>
</div>

  <!-- Example row of columns -->
      <div class="row">
        <div class="col-lg-4">
          <h2>Safari bug warning!</h2>
          <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
       </div>
        <div class="col-lg-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details &raquo;</a></p>
        </div>
      </div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<div class="row">
	<div class="col-md-12">
		<%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"})do |f| %>
          <div class="form-group">
            <div class="control-label col-md-2">
              <%= f.label :name %>
            </div>
            <div class="col-md-8">
              <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>	
            </div>
         </div>
         <div class="form-group">
           <div class="control-label col-md-2">
           	 <%= f.label :description %>
           </div>
           <div class="col-md-8">
           	  <%= f.text_area :description, rows:10, class: "form-control", placeholder: "Enter steps to create recipe" %>
           </div>
           <div class="form-group">
           	  <div class="col-md-offset-2 col-md-10">
           	  	<%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
           	  </div>
           </div>
        <% end %> 
        <div class=" col-md-4 col-md-offset-4 colormatch">
        	[<%= link_to "cancel request and return to recipes listing" %>]
        </div> 
    </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="row">
   <div class="cold-md-2">
    <section class="chef_info center">
	   <%= gravatar_for(recipe.chef, size:120) %>
    </section>
  </div>
<div class="cold-md-8 well">
 <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
 <p><%= truncate(recipe.description, length: 150) %></p>
<p>
  <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small></span>
   </p>
 </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>


<div align="center">
  <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
<%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "create a new recipe" %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: "showing all recipes" %>
<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong>Steps: </strong></h4>
  <hr />
  <%= simple_format(@recipe.description) %>
  <hr />
  <div class="pull-right">
  <p class="center">
  	<em>Created by:</em>
  </p>	
  <p class="center">
  	 <%= link_to gravatar_for(@recipe.chef), recipes_path %>
  </p>
  <p class="center">
  	<small><%= @recipe.chef.chefname.capitalize %></small>
  	<div class="pull-right"> <%= time_ago_in_words(@recipe.created_at) %> ago</div>
  </p>
  </div>
  <div class="recipe-actions">
    <%= link_to "Edit this recipe", edit_recipe_path(@recipe), class: 'btn btn-xs btn-warning' %>
    <%= link_to "Delete this recipe", recipes_path(@recipe), method: :delete, data: { confirm: "Are you sure you want to delete this recipe?" }, class: "btn btn-xs btn-danger" %>
  <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>
</div>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  	 <div class="panel panel-danger">
  	   <div class="panel-heading">
  	 	<h2 class="panel-title">
  	 		<%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
  	 	</h2>
  	 	<div class="panel-body">
  	 		<ul>
             <% obj.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
            </ul>
  	 	  </div>
  	    </div>
  	  </div>
    </div>	
  </div>
<% end %>   

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />

app/views/shared/page_title.html.erb
<h1 align="center"><%= title.capitalize %></h1>
<hr />